"""Physical-card domain models, identity helpers, persistence, and service."""

from emercard.modules.cards.errors import (
    CardAlreadyAssignedError,
    CardAlreadyIssuedError,
    CardAssignmentTargetInvalidError,
    CardEncodingMismatchError,
    CardEncodingNotVerifiedError,
    CardError,
    CardIdentityConflictError,
    CardInvalidTransitionError,
    CardInvariantError,
    CardLinkAlreadyProvisionedError,
    CardNotFoundError,
    CardOwnershipMismatchError,
    CardProvisioningError,
    CardReassignmentNotAllowedError,
    CardReplacementError,
    CardSerialConflictError,
    CardTerminalStateError,
    CardTokenHashConflictError,
    CardUserNotFoundError,
)
from emercard.modules.cards.identity import (
    CROCKFORD_ALPHABET,
    generate_public_token,
    generate_serial,
    hash_public_token,
    normalize_serial,
    validate_token_hash,
)
from emercard.modules.cards.models import (
    CardDocument,
    CardLinkProvisioningResult,
    CardProvisioningResult,
    CardStatus,
)
from emercard.modules.cards.operations import CustodyEventRepository, IdempotencyRepository
from emercard.modules.cards.repository import CardRepository
from emercard.modules.cards.schemas import (
    AdminCardOutput,
    AssignCardInput,
    BlankCardCreateInput,
    CardListOutput,
    CardOwnerOutput,
    CardProvisioningOutput,
    ConfirmEncodingInput,
    ProvisioningOutput,
    ReassignCardInput,
    SafeUserOutput,
    encoding_state,
    to_admin_card,
)
from emercard.modules.cards.service import (
    CardRepositoryProtocol,
    CardService,
    UserRepositoryProtocol,
)

__all__ = [
    "CROCKFORD_ALPHABET",
    "CardAlreadyAssignedError",
    "CardAlreadyIssuedError",
    "CardAssignmentTargetInvalidError",
    "CardDocument",
    "CardEncodingMismatchError",
    "CardEncodingNotVerifiedError",
    "CardError",
    "CardIdentityConflictError",
    "CardInvalidTransitionError",
    "CardInvariantError",
    "CardLinkAlreadyProvisionedError",
    "CardNotFoundError",
    "CardOwnershipMismatchError",
    "CardProvisioningError",
    "CardReassignmentNotAllowedError",
    "CardProvisioningResult",
    "CardLinkProvisioningResult",
    "AdminCardOutput",
    "AssignCardInput",
    "BlankCardCreateInput",
    "CardListOutput",
    "CardOwnerOutput",
    "CardProvisioningOutput",
    "ConfirmEncodingInput",
    "ProvisioningOutput",
    "ReassignCardInput",
    "SafeUserOutput",
    "CardRepository",
    "CardRepositoryProtocol",
    "CustodyEventRepository",
    "CardReplacementError",
    "CardSerialConflictError",
    "CardService",
    "CardStatus",
    "CardTerminalStateError",
    "CardTokenHashConflictError",
    "CardUserNotFoundError",
    "UserRepositoryProtocol",
    "IdempotencyRepository",
    "generate_public_token",
    "generate_serial",
    "hash_public_token",
    "normalize_serial",
    "validate_token_hash",
    "encoding_state",
    "to_admin_card",
]
